# This is a basic workflow to help you get started with Actions

name: refresh-from-upstream

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the next branch
on:
  schedule:
    - cron: "5 5 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:    
  refresh-7_14:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:          
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - run: |
          git remote add camunda https://github.com/camunda/docker-camunda-bpm-platform.git
      - run: git fetch camunda
      - run: git checkout 7.14-apiauth-adminuser-group0
      - run: git config --global user.email "none"
      - run: git config --global user.name "github-workflow"
      - run: git merge camunda/7.14
      - run: git push

                  
  refresh-next:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:          
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - run: |
          git remote add camunda https://github.com/camunda/docker-camunda-bpm-platform.git
      - run: git fetch camunda
      - run: git checkout next-apiauth-adminuser-group0
      - run: git config --global user.email "none"
      - run: git config --global user.name "github-workflow"
      - run: git merge camunda/next
      - run: git push
          
